version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: frostwillmott/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    image: frostwillmott/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: frostwillmott/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
